const data = {
     products: [
        {
            // _id: '1',
            name: 'Speaker',
            prod: 'sony-speaker',
            image: '/images/speaker.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '2',
            name: 'americano',
            prod: 'door-bell',
            image: '/images/speaker.jpg',
            price: 320,
            countInStock: 10,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '3',
            name: 'Hondola',
            prod: 'car-alarm',
            image: '/images/speaker.jpg',
            price: 220,
            countInStock: 10,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '4',
            name: 'Callowly',
            prod: 'golf-ball',
            image: '/images/speaker.jpg',
            price: 920,
            countInStock: 3,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        
     ],
};

export default data;