const data = {
     products: [
        {
            // _id: '1', 3 third part get rid of _id because they will be assing automatcaty by mongodb
            name: 'Speaker',
            prod: 'sony-speaker',
            image: '/images/speaker.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '2',
            name: 'americano',
            prod: 'door-bell',
            image: '/images/speaker.jpg',
            price: 320,
            countInStock: 10,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '3',
            name: 'Hondola',
            prod: 'car-alarm',
            image: '/images/speaker.jpg',
            price: 220,
            countInStock: 10,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '4',
            name: 'Callowly',
            prod: 'golf-ball',
            image: '/images/speaker.jpg',
            price: 921,
            countInStock: 3,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '5',
            name: 'Rolex',
            prod: 'Third genarationn',
            image: '/images/speaker.jpg',
            price: 921,
            countInStock: 3,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '6',
            name: 'Garmin',
            prod: 'Golf leaser',
            image: '/images/speaker.jpg',
            price: 921,
            countInStock: 3,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },
        {
            // _id: '7',
            name: 'Hubloter watch 2022',
            prod: 'Hubloter',
            image: '/images/speaker.jpg',
            price: 921,
            countInStock: 3,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Smart watch Heart Monitor',
        },
        {
            // _id: '8',
            name: 'Ring Viddeo Doorbell',
            prod: 'Doorbell',
            image: '/images/speaker.jpg',
            price: 921,
            countInStock: 3,
            brand: 'Sony',
            rating: 4.5,
            numReviews: 10,
            description: 'Sony speaker waterproof',
        },

        
        
        
     ],
};

export default data;